title: Jeremy Yang
logo: /assets/img/logo.png
description: I'm a final year PhD candidate at MIT Sloan School of Management advised by Sinan Aral, Dean Eckles and Juanjuan Zhang. 
Yoshow_downloads: true
I'm currently on the academic job market 
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
