title: Jeremy Yang
logo: /assets/img/logo.png
description: I'm a final year PhD candidate at MIT Sloan School of Management. I'm currently on the marketing academic job market.
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
