title: Jeremy Z Yang
tagline: Jeremy Yang. Jeremy Z Yang. I'm a PhD candidate at MIT Sloan School of Management. 
logo: /assets/img/profile3.png
description: I'm a PhD candidate at MIT Sloan School of Management. I'm looking for faculty position in business schools that start in summer 2021.
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
