title: Jeremy Z Yang
tagline: Jeremy Yang. Jeremy Z Yang. I'm a PhD candidate at MIT Sloan School of Management. 
logo: /assets/img/profile.png
description: I'm a PhD candidate at MIT Sloan School of Management. I'm on the marketing academic job market in 2020/2021.
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
