title: Jeremy Z Yang
logo: /assets/img/logo.png
description: I'm a PhD candidate at MIT Sloan School of Management. I'm on the marketing academic job market in 2020/2021.
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
