title: Jeremy Z Yang
tagline: Jeremy Yang. Jeremy Z Yang. PhD. MIT Sloan School of Management. Marketing. Information Systems. Data Science. Business School. Faculty. Professor.
logo: /assets/img/profile5.png
description: I'm a PhD candidate at MIT Sloan School of Management. 
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
