title: Jeremy Yang
logo: /assets/img/logo.png
description: I'm a final year PhD candidate in Management at MIT Sloan. I'm currently on the academic job market.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
