title: Jeremy Yang
logo: /assets/img/logo.png
description: I'm a PhD candidate in Management at MIT. I'm currently on the marketing academic job market.
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
